name = "ironshield"
main = "build/worker/shim.mjs"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]

[build]
command = "node build.js && rustup run stable worker-build --release"
[[routes]]
pattern = "pow.ironshield.cloud"
zone_name = "ironshield.cloud"
custom_domain = true