name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          # Use nightly toolchain for WASM threading support
          toolchain: nightly
          profile: minimal
          override: true
          # Specify the target for the runner environment
          target: x86_64-unknown-linux-gnu 
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build Project
        # Step 1: Explicitly run the build command from wrangler.toml
        run: node build.js && cargo install -q worker-build && worker-build --release
      
      - name: Publish to Cloudflare
        # Step 2: Tell the action to ONLY publish, assuming build is done
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish # Explicitly tell the action to publish 